name: apply adapta label and build android development

on:
  workflow_dispatch:

jobs:
  build_android_development:
    runs-on: macOS-latest
    env:
      JAVA_VERSION: '12.x'
      FLUTTER_VERSION: '2.5.0'
      LABEL_NAME: 'hello_adapta'
      LABEL: 'Hello Adapta'
      GOOGLE_CHAT_WEBHOOK: ${{ secrets.DEMO_GOOGLE_CHAT_WEBHOOK }}
      DEMO_BASE_URL: ${{ secrets.DEMO_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION_NAME: 'github_actions'
      ARTIFACTS: 'build/app/outputs/apk/release/*.apk'
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - uses: Adapta-Innovation/checkout@v2
      - uses: Adapta-Innovation/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: Adapta-Innovation/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: apply hello_buurtzorg
        run: sh ./generate_label_files.sh ${{ env.LABEL_NAME }} "${{ env.LABEL }}"
      - name: Build Android App
        run: flutter build apk --obfuscate --split-debug-info=./hello_adapta/symbols --dart-define=BASE_URL=${{ secrets.DEV_BASE_URL }} --dart-define=EXEC_ENV='github_actions' --dart-define=LABEL='hello_buurtzorg'
      - name: Release Apps
        uses: Adapta-dev/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}_adapta
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk'
