name: drive android development - Buurtzorg

on:
  workflow_dispatch:

jobs:
  drive_android_development:
    runs-on: macos-latest
    env:
      JAVA_VERSION: '12.x'
      FLUTTER_VERSION: '2.5.0'
      LABEL_NAME: 'hello_buurtzorg'
      LABEL_TEXT: 'Buurtzorg'
      GOOGLE_CHAT_WEBHOOK: ${{ secrets.DEMO_GOOGLE_CHAT_WEBHOOK }}
      DEMO_BASE_URL: ${{ secrets.DEMO_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION_NAME: 'github_actions'
      ARTIFACTS: 'screenshots/*.png'
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default, google_apis]
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - uses: Adapta-Innovation/checkout@v2
      - uses: Adapta-Innovation/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: Adapta-Innovation/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Apply Label
        run: sh ./generate_label_files.sh ${{ env.LABEL_NAME }} "${{ env.LABEL_TEXT }}"
      - name: Run Flutter Driver tests
        uses: Adapta-Innovation/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          profile: pixel
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --dart-define=BASE_URL=${{ env.DEMO_BASE_URL }} --dart-define=EXEC_ENV=${{ env.GITHUB_ACTION_NAME }} --dart-define=LABEL=${{ env.LABEL_NAME }}
      - name: Release screenshots
        uses: Adapta-Innovation/release-action@v1
        with:
          tag: "${{ env.APP_VERSION }}_${{ matrix.target }}_${{ matrix.api-level }}"
          name: "${{ env.APP_VERSION }}_${{ matrix.target }}_${{ matrix.api-level }}_${{ env.LABEL_NAME }}"
          token: ${{ env.GITHUB_TOKEN }}
          artifacts: ${{ env.ARTIFACTS }
