name: flutter drive ios

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  drive:
    strategy:
      matrix:
        device:
        - "iPhone 8 (14.4)"
        - "iPhone 11 Pro Max (14.4)"
      # When set to true, GitHub cancels all in-progress jobs if any matrix job
      # fails.
      fail-fast: false
    runs-on: macOS-latest
    steps:
    - name: "List all simulators"
      run: "xcrun instruments -s"
    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )

        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    # The branch or tag ref that triggered the workflow will be checked out.
    # https://github.com/actions/checkout
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    - name: "Run Flutter Driver tests"
      run: "flutter drive --target=test_driver/app.dart"
      env:
        BASE_URL: ${{ secrets.DEV_BASE_URL }}
        EXEC_ENV: 'github_actions'
