name: build ios development - Buurtzorg

on:
  workflow_dispatch:

jobs:
  build_ios_development:
    runs-on: macOS-latest
    env:
      JAVA_VERSION: '12.x'
      FLUTTER_VERSION: '2.5.0'
      LABEL_NAME: 'hello_buurtzorg'
      LABEL_TEXT: 'Buurtzorg'
      GOOGLE_CHAT_WEBHOOK: ${{ secrets.DEMO_GOOGLE_CHAT_WEBHOOK }}
      DEMO_BASE_URL: ${{ secrets.DEMO_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION_NAME: 'github_actions'
      ARTIFACTS: 'build/ios/iphoneos/app.ipa'
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - uses: Adapta-Innovation/checkout@v2
      - uses: Adapta-Innovation/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: Adapta-Innovation/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Apply Label
        run: sh ./generate_label_files.sh ${{ env.LABEL_NAME }} "${{ env.LABEL_TEXT }}"
      - name: flutter pub get
        run: flutter pub get
      - name: Build iOs App
        run: |
          flutter build ios --no-codesign --dart-define=BASE_URL=${{ env.DEMO_BASE_URL }} --dart-define=EXEC_ENV=${{ env.GITHUB_ACTION_NAME }} --dart-define=LABEL=${{ env.LABEL_NAME }}
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Release Apps
        uses: Adapta-Innovation/release-action@v1
        with:
          tag: "${{ env.APP_VERSION }}"
          name: "${{ env.APP_VERSION }}_${{ env.LABEL_NAME }}"
          token: ${{ env.GITHUB_TOKEN }}
          artifacts: ${{ env.ARTIFACTS }}
