name: flutter drive android

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  drive:
    strategy:
      matrix:
        api-level: [ 21, 29 ]
        target: [ default ]
      # When set to true, GitHub cancels all in-progress jobs if any matrix job
      # fails.
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    - name: Run Flutter Driver tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: flutter drive --target=test_driver/app.dart
