name: drive android development

on:
  workflow_dispatch:

jobs:
  drive_android_development:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '12.x'
      FLUTTER_VERSION: '2.5.0'
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default, google_apis]
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - uses: Adapta-dev/checkout@v2
      - uses: Adapta-dev/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: Adapta-dev/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          profile: pixel
          script: flutter drive --target=test_driver/app.dart --dart-define=BASE_URL=${{ secrets.DEV_BASE_URL }} --dart-define=EXEC_ENV='github_actions'
      - name: Release screenshots
        uses: Adapta-dev/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}_${{ matrix.target }}_${{ matrix.api-level }}
          name: ${{ env.APP_VERSION }}_${{ matrix.target }}_${{ matrix.api-level }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: '*.png'
